### ISSUE TITLE
About "head.obj"

### ISSUE THREAD

**Issue by EricStuart** [c-he/perm#2]
thanks for your amazing work!

Could you please provide the head.obj used in this repo or show some steps how to get the substitute?

**Comment by YoussefBenCheikh** [comment]
Amazing work ! thank you.
I also need the head.obj please.

**Comment by digital-salon** [comment]
Hi, thanks for your interest in our work! Our vendor says they will release a public link for the head mesh, and we are not allowed to share the mesh personally. Will keep you updated when the mesh link is available.

**Comment by c-he** [comment]
Hi all, thanks for your interest in our work! Our vendor says they will release a public link for the head mesh, and we are not allowed to share the mesh personally. Will keep you updated when the mesh link is available.

**Comment by EricStuart** [comment]
> Hi all, thanks for your interest in our work! Our vendor says they will release a public link for the head mesh, and we are not allowed to share the mesh personally. Will keep you updated when the mesh link is available.

Thanks for your quick response, looking forward to the good news

**Comment by c-he** [comment]
Hi all, our vendor just provided the link to the head mesh. You can download it from: https://www.avatarneo.com/PinscreenGenericHeadModel.obj

**Comment by YoussefBenCheikh** [comment]
Thank you !
